[package]
name = "cw-signed-decimal"
version = "0.1.0"
authors = ["Tomasz Kopacki <tk-o@users.noreply.github.com>"]
edition = "2018"
description = "CosmWasm Signed Decimal"
license = "Apache-2.0"
repository = "https://github.com/tk-o/cw-signed-decimal"

[dependencies]
cosmwasm-std = { version = "0.16.7" }